#include "cpu/exec/template-start.h"

JCC_COND(a, ~(cpu.eflags.ZF | cpu.eflags.CF))
JCC_COND(ae, ~cpu.eflags.CF)
JCC_COND(b, cpu.eflags.CF)
JCC_COND(be, cpu.eflags.ZF | cpu.eflags.CF)
JCC_COND(c, cpu.eflags.CF)
JCC_COND(cxz, ~REG(R_CX))
JCC_COND(ecxz, ~REG(R_ECX))
JCC_COND(e, cpu.eflags.ZF)
JCC_COND(g, ~cpu.eflags.ZF & ~(cpu.eflags.SF ^ cpu.eflags.OF))
JCC_COND(ge, ~(cpu.eflags.SF ^ cpu.eflags.OF))
JCC_COND(l, cpu.eflags.SF ^ cpu.eflags.OF)
JCC_COND(le, cpu.eflags.ZF | (cpu.eflags.SF ^ cpu.eflags.OF))
JCC_COND(na, cpu.eflags.CF | cpu.eflags.ZF)
JCC_COND(nae, cpu.eflags.CF)
JCC_COND(nb, ~cpu.eflags.CF)
JCC_COND(nbe, ~cpu.eflags.CF & ~cpu.eflags.CF)
JCC_COND(nc, ~cpu.eflags.CF)
JCC_COND(ne, ~cpu.eflags.ZF)
JCC_COND(ng, cpu.eflags.ZF | (cpu.eflags.SF ^ cpu.eflags.OF))
JCC_COND(nge, cpu.eflags.SF ^ cpu.eflags.OF)
JCC_COND(nl, ~(cpu.eflags.SF ^ cpu.eflags.OF))
JCC_COND(nle, ~cpu.eflags.ZF & ~(cpu.eflags.SF ^ cpu.eflags.OF))
JCC_COND(no, ~cpu.eflags.OF)
JCC_COND(np, ~cpu.eflags.PF)
JCC_COND(ns, ~cpu.eflags.SF)
JCC_COND(nz, ~cpu.eflags.ZF)
JCC_COND(o, cpu.eflags.OF)
JCC_COND(p, cpu.eflags.PF)
JCC_COND(pe, cpu.eflags.PF)
JCC_COND(po, ~cpu.eflags.PF)
JCC_COND(s, cpu.eflags.SF)
JCC_COND(z, cpu.eflags.ZF)

#include "cpu/exec/template-end.h"