#include "cpu/exec/template-start.h"

CMOVCC_COND(a, !(cpu.eflags.ZF | cpu.eflags.CF))
CMOVCC_COND(ae, !cpu.eflags.CF)
CMOVCC_COND(b, cpu.eflags.CF)
CMOVCC_COND(be, cpu.eflags.ZF | cpu.eflags.CF)
CMOVCC_COND(c, cpu.eflags.CF)
CMOVCC_COND(cxz, !REG(R_CX))
CMOVCC_COND(ecxz, !REG(R_ECX))
CMOVCC_COND(e, cpu.eflags.ZF)
CMOVCC_COND(g, !cpu.eflags.ZF & !(cpu.eflags.SF ^ cpu.eflags.OF))
CMOVCC_COND(ge, !(cpu.eflags.SF ^ cpu.eflags.OF))
CMOVCC_COND(l, cpu.eflags.SF ^ cpu.eflags.OF)
CMOVCC_COND(le, cpu.eflags.ZF | (cpu.eflags.SF ^ cpu.eflags.OF))
CMOVCC_COND(na, cpu.eflags.CF | cpu.eflags.ZF)
CMOVCC_COND(nae, cpu.eflags.CF)
CMOVCC_COND(nb, !cpu.eflags.CF)
CMOVCC_COND(nbe, !cpu.eflags.CF & !cpu.eflags.CF)
CMOVCC_COND(nc, !cpu.eflags.CF)
CMOVCC_COND(ne, !cpu.eflags.ZF)
CMOVCC_COND(ng, cpu.eflags.ZF | (cpu.eflags.SF ^ cpu.eflags.OF))
CMOVCC_COND(nge, cpu.eflags.SF ^ cpu.eflags.OF)
CMOVCC_COND(nl, !(cpu.eflags.SF ^ cpu.eflags.OF))
CMOVCC_COND(nle, !cpu.eflags.ZF & !(cpu.eflags.SF ^ cpu.eflags.OF))
CMOVCC_COND(no, !cpu.eflags.OF)
CMOVCC_COND(np, !cpu.eflags.PF)
CMOVCC_COND(ns, !cpu.eflags.SF)
CMOVCC_COND(nz, !cpu.eflags.ZF)
CMOVCC_COND(o, cpu.eflags.OF)
CMOVCC_COND(p, cpu.eflags.PF)
CMOVCC_COND(pe, cpu.eflags.PF)
CMOVCC_COND(po, !cpu.eflags.PF)
CMOVCC_COND(s, cpu.eflags.SF)
CMOVCC_COND(z, cpu.eflags.ZF)

#include "cpu/exec/template-end.h"